codalab/apps/teams/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^(?P<competition_pk>\d+)/$', views.TeamDetailView.as_view(), name='team_detail'),
    url(r'^(?P<competition_pk>\d+)/create$', views.TeamCreateView.as_view(), name='team_new'),
    url(r'^(?P<competition_pk>\d+)/(?P<team_pk>\d+)/edit/$', views.TeamEditView.as_view(), name='team_edit'),
    url(r'^(?P<competition_pk>\d+)/(?P<team_pk>\d+)/delete/$', views.TeamCancelView.as_view(), name='team_delete'),
    url(r'^(?P<competition_pk>\d+)/(?P<request_pk>\d+)/(?P<action>accept|reject|cancel)/$', views.RequestTeamView.as_view(), name='team_request_action'),
    url(r'^(?P<competition_pk>\d+)/request/(?P<team_pk>\d+)/$', views.NewRequestTeamView.as_view(), name='team_enrol'),
    url(r'^(?P<competition_pk>\d+)/create_org_team/$', views.CompetitionOrganizerTeams.as_view(), name='create_org_team'),
    url(r'^(?P<competition_pk>\d+)/create_org_teams_from_csv/$', views.CompetitionOrganizerCSVTeams.as_view(), name='create_org_teams_from_csv'),
    url(r'^(?P<competition_pk>\d+)/edit_org_team/(?P<pk>\d+)$', views.CompetitionOrganizerTeams.as_view(), name='edit_org_team'),
    url(r'^(?P<competition_pk>\d+)/delete_org_team/(?P<team_pk>\d+)$', views.delete_organizer_team, name='delete_org_team'),
)

codalab/codalab/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from apps.web.views import MyAdminView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('apps.web.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^clients/', include('apps.authenz.urls')),
    url(r'^api/', include('apps.api.routers')),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin_monitoring_links/$', MyAdminView.as_view(), name='admin_monitoring_links'),
    url(r'^teams/', include('apps.teams.urls')),
    url(r'^newsletter/', include('apps.newsletter.urls', app_name='newsletter', namespace='newsletter')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^hidden-admin/', include(admin.site.urls)),

    url(r'^', include('pin_passcode.urls')),

    # Switch User
    url(r"^su/", include("django_switchuser.urls")),

    # Static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),

    # Media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # JS Reverse for saner AJAX calls
    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse')
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

codalab/apps/teams/models.py
import logging
import os
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.utils.functional import cached_property
from django import template
import apps.web as web
from apps.web.utils import PublicStorage, BundleStorage
from datetime import datetime, timedelta

register = template.Library()
User = settings.AUTH_USER_MODEL
logger = logging.getLogger(__name__)


def get_competition_teams(competition):
    team_list=Team.objects.filter(
        competition=competition,
        status=TeamStatus.objects.get(codename="approved"),
    ).all()
    return team_list


def get_competition_pending_teams(competition):
    team_list=Team.objects.filter(
        competition=competition,
        status=TeamStatus.objects.get(codename="pending"),
    ).select_related("status").all()

    return team_list


def get_team_pending_membership(team):
    requests = TeamMembership.objects.filter(
        team=team,
        is_request=True,
        status=TeamMembershipStatus.objects.get(codename="pending"),
    ).select_related("user").all()
    return requests


def get_competition_deleted_teams(competition):
    team_list=Team.objects.filter(
        competition=competition,
        status=TeamStatus.objects.get(codename="deleted"),
    ).all()

    return team_list


def get_competition_user_teams(competition,user):
    team_list=Team.objects.filter(
        competition=competition,
        status=TeamStatus.objects.get(codename="approved"),
        creator=user.user,
    ).all()
    if len(team_list)==0:
        team_list=None
    else:
        team_list=team_list[0]
    return team_list


def get_competition_user_pending_teams(competition,user):
    team_list=Team.objects.filter(
        competition=competition,
        status=TeamStatus.objects.get(codename="pending"),
        creator=user.user,
    ).all()
    if len(team_list)==0:
        team_list=None
    else:
        team_list=team_list[0]
    return team_list


def get_user_requests(user, competition):
    team_list = get_competition_teams(competition)
    user_requests = TeamMembership.objects.filter(
        user=user.user,
        team__in=team_list,
    ).all()
    return user_requests


def get_allowed_teams(user,competition):
    # TODO: Remove teams where user already have a request
    return get_competition_teams(competition)


# def get_user_team(user, competition):
def get_user_team(participant, competition):
    # This function just gets user's created teams that are approved
    # and returns the first one or None
    user_created_teams = Team.objects.filter(competition=competition, creator=participant.user, status__codename='approved').select_related('status')
    # If we have user created teams
    if user_created_teams is not None and len(user_created_teams) > 0:
        return user_created_teams[0]
    else:
        # Else if no user created teams
        user_approved_team_memberships = list(participant.user.team_memberships.filter(status__codename='approved').select_related('team', 'status'))
        user_approved_active_teams = [membership for membership in user_approved_team_memberships if membership.is_active]
        if user_approved_active_teams is not None and len(user_approved_active_teams) > 0:
            return user_approved_active_teams[0].team
    return None

def get_team_submissions(team, phase=None):
    if phase is None:
        t_s = web.models.CompetitionSubmission.objects.filter(phase=phase, team=team)
    else:
        t_s = web.models.CompetitionSubmission.objects.filter(team=team)

    return t_s


def get_last_team_submissions(team, days=1):
    return web.models.CompetitionSubmission.objects.filter(team=team, submitted_at__gte=datetime.now()-timedelta(days))


def get_team_submissions_inf(team, phase):

    submissions = web.models.CompetitionSubmission.objects.filter(
        team=team,
        phase=phase
    ).select_related('status').order_by('-submitted_at')

    # find which submission is in the leaderboard, if any and only if phase allows seeing results.
    id_of_submission_in_leaderboard = -1
    if phase and not phase.is_blind:
        leaderboard_entry = web.models.PhaseLeaderBoardEntry.objects.filter(
            board__phase=phase,
            result__team=team
        ).select_related('result', 'result__participant')
        if leaderboard_entry:
            id_of_submission_in_leaderboard = leaderboard_entry[0].result.pk
    submission_info_list = []
    for submission in submissions:
        submission_info = {
            'id': submission.id,
            'number': submission.submission_number,
            'username': submission.participant.user.username,
            'filename': submission.get_filename(),  # left as call for legacy update of readable_filename on subs.
            'submitted_at': submission.submitted_at,
            'status_name': submission.status.name,
            'is_finished': submission.status.codename == 'finished',
            'is_in_leaderboard': submission.id == id_of_submission_in_leaderboard,
            'exception_details': submission.exception_details,
            'description': submission.description,
            'team_name': submission.team_name,
            'method_name': submission.method_name,
            'method_description': submission.method_description,
            'project_url': submission.project_url,
            'publication_url': submission.publication_url,
            'bibtex': submission.bibtex,
            'organization_or_affiliation': submission.organization_or_affiliation,
            'is_public': submission.is_public,
            'score': submission.get_default_score(),
        }
        submission_info_list.append(submission_info)

    return submission_info_list


def get_available_participants(competition):
    return []


class TeamStatus(models.Model):
    UNKNOWN = 'unknown'
    DENIED = 'denied'
    APPROVED = 'approved'
    PENDING = 'pending'
    DELETED = 'deleted'
    name = models.CharField(max_length=30)
    codename = models.CharField(max_length=30,unique=True)
    description = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Team(models.Model):
    """ This is the base team. """
    class Meta:
        unique_together = (('name', 'competition'),)

    def __unicode__(self):
        return "[%s] %s - %s" % (self.status.codename, self.competition.title, self.name)

    name = models.CharField(max_length=100, null=False, blank=False)
    competition = models.ForeignKey('web.Competition')
    description = models.TextField(null=True, blank=True)
    image = models.FileField(upload_to='team_logo', storage=PublicStorage, null=True, blank=True, verbose_name="Logo")
    image_url_base = models.CharField(max_length=255)
    allow_requests = models.BooleanField(default=True, verbose_name="Allow requests")
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='team_creator')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='TeamMembership', blank=True, null=True, related_name='teams')
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    last_modified = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey(TeamStatus, null=True)
    reason = models.CharField(max_length=100,null=True,blank=True)

    def save(self, *args, **kwargs):
        # Make sure the image_url_base is set from the actual storage implementation
        self.image_url_base = self.image.storage.url('')
        self.last_modified=now()

        if self.status is None:
            self.status = TeamStatus.objects.get(codename=TeamStatus.PENDING)

        # Do the real save
        return super(Team,self).save(*args,**kwargs)

    @cached_property
    def image_url(self):
        # Return the transformed image_url
        if self.image:
            return os.path.join(self.image_url_base, self.image.name)
        return None

    @cached_property
    def active_members(self):
        return self.get_members("approved")

    @cached_property
    def active_members_count(self):
        return len(self.get_members("approved")) + 1

    @cached_property
    def active_requests(self):
        return self.get_members("pending")

    def has_applied(self, user):
        for member in self.get_members("pending"):
            if member.user == user:
                return True
        return False

    def is_member(self, user):
        for member in self.get_members("approved"):
            if member.user == user:
                return True
        return False

    @property
    def is_admin(self, user):
        return self.creator==user

    def get_members(self, status):
        requests = TeamMembership.objects.filter(
            team=self,
            is_request=True,
            status=TeamMembershipStatus.objects.get(codename=status),
        ).select_related("user").all()

        members=[]
        for member in requests:
            if member.is_active:
                members.append(member)

        return members


class TeamMembershipStatus(models.Model):
    UNKNOWN = 'unknown'
    REJECTED = 'rejected'
    APPROVED = 'approved'
    PENDING = 'pending'
    CANCELED = 'canceled'
    name = models.CharField(max_length=30)
    codename = models.CharField(max_length=30,unique=True)
    description = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class TeamMembership(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='team_memberships')
    team = models.ForeignKey(Team)
    is_invitation = models.BooleanField(default=False)
    is_request = models.BooleanField(default=False)
    start_date = models.DateTimeField(null=True, blank=True, verbose_name="Start Date (UTC)")
    end_date = models.DateTimeField(null=True, blank=True, verbose_name="End Date (UTC)")
    message = models.TextField(null=True, blank=True)

codalab/apps/teams/templates/teams/competitions/organizer_csv_teams.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load codalab_tags %}
{% load tz %}

{% block page_title %}Participants{% endblock page_title %}
{% block head_title %}Participants{% endblock %}

{% block extra_head %}
    <script src="{% static 'js/foundation/vendor/jquery.validate.min.js' %}"></script>
{% endblock %}

{% block content %}
    <a href="{% url "competitions:view" pk=competition.pk %}" class="pull-right">Go Back to Competition Homepage</a>
    {{ form.non_field_errors }}
    <div id="main_container" class="container-fluid">
    <form id="choose-file" action="{% url "create_org_teams_from_csv" competition_pk=competition.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="panel_container" class="panel panel-default">
            <div id="info_container">The CSV File should be formatted with the teams in each row, where the team name is
                the first entry, and team members are separated by commas.
            </div>
        <button id="submit_button" type="button" class="pull-middle btn btn-primary">Submit Teams from CSV</button>
            <div id="code">
                Example CSV:
                <table>
                    <tr>
                        <td>TeamOne, Team Member 1, Team Member 2, Team Member 3,<br/>TeamTwo, Team Member 1, Team Member 2</td>
                    </tr>
                </table>
            </div>
        </div>
        </form>
    </div>
<style>
    #main_container {
        text-align: center;
        margin: auto;
        padding: 3em;
    }
    #code {
        border:solid gray;
        border-width:.1em .1em .1em .8em;
        padding:.2em .6em;
        overflow: auto;
        width: 70%;
        margin: auto;
        text-align: left;
        background: #f0f0f0;
        font-family: Monospace;
    }
    table {
        text-align: left;
        width: 100%;
        background: #f0f0f0;
    }
    #panel_container {
        margin: auto;
        width: inherit;
        padding-bottom: 6em;
        padding-top: 4em;
        text-align: center;
    }
    #info_container {
        width: 90%;
        font-size: 19px;
        margin: auto;
        height: 4em;
    }
    #choose-file>p {
        display: none;
    }
    #submit_button {
        margin: 1em auto;
    }
    @media only screen and (max-width: 991px) {
        #info_container {
            font-size: 15px;
            height: 5em;
        }
        #code {
            width: auto;
        }
    }
    @media only screen and (max-width: 671px) {
        #code {
            font-size: 13px;
            width: auto;
        }
    }
    @media only screen and (max-width: 570px) {
        #code {
            font-size: 11px;
            width: auto;
        }
    }
    @media only screen and (max-width: 477px) {
        #info_container {
            font-size: 13px;
            height: 5em;
        }
    }
</style>
<script>
    $( document ).ready(function() {
        $("#submit_button").click(function () {
            $('#id_csv_file').click();
        });
        $('#id_csv_file').change(function(){
            $('#choose-file').submit()
        });
        var errors = document.getElementsByClassName("errorlist");
        if (errors[0].innerText !== ""){
            errors[0].classList.add('list-unstyled');
            errors[0].children[0].classList.add('alert');
            errors[0].children[0].classList.add('alert-danger');
            $('.alert.alert-danger').css({
                'margin': '2em auto 0 auto',
                'text-align': 'center',
                'border-radius': '4px',
                'width': '50%'
        })
        }
    });
</script>
{% endblock %}

codalab/apps/teams/templates/teams/competitions/organizer_teams.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load codalab_tags %}
{% load tz %}

{% block page_title %}Participants{% endblock page_title %}
{% block head_title %}Participants{% endblock %}

{% block extra_head %}
    <script src="{% static 'js/foundation/vendor/jquery.validate.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="comp-back">
        <a href="{% url "competitions:view" pk=form.competition.pk %}" class="pull-right">Go Back to Competition Homepage</a>
    </div>
    <div id="main_container" class="container-fluid">
        <div class="form-group {% if form.non_field_errors %}alert alert-danger{% endif %}">
            {{ form.non_field_errors }}
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="panel_container" class="panel panel-default">
                <div class="form-group">
                    <label for="id_name">Team Name:</label>
                    <input id="id_name" maxlength="100" name="name" type="text" value="{{ form.name.value|default_if_none:"" }}"/>
                    <p>{{ form.name.errors }}</p>
                </div>
                <div class="form-group">
                    <label for="id_text_members">Team Members:</label>
                    <textarea class="form-control" rows="3" id="id_text_members" name="text_members" placeholder="Enter team member names separated by commas. (Ex. Team Member1, Team Member 2, etc.)">{{ initial_team_members|default_if_none:"" }}</textarea>
                    <p>{{ form.text_members.error }}</p>
                </div>
                <div class="form-group">
                    <label for="id_description">Description:</label>
                    <textarea class="form-control" rows="3" id="id_description" name="description" placeholder="Enter a short description of the team here.">{{ form.description.value|default_if_none:"" }}</textarea>
                    <p>{{ form.description.error }}</p>
                </div>
                <div id="pull-middle">
                    <input id="submit_button" type="submit" class="pull-middle btn btn-primary" value="Submit Team">
                </div>
            </div>
        </form>
    </div>
    <style>
        #main_container {
            text-align: left;
            margin: 0 auto;
            padding: 1em;
        }

        #id_name {
            width: 40%;
        }

        .form-group {
            width: 96%;
            margin: 0.5em auto;
        }

        #panel_container {
            margin: 1em auto;
            width: 80%;
            padding-bottom: 2em;
            padding-top: 1em;
        }

        #pull-middle {
            text-align: center;
        }

        #submit_button {
            margin: 1em auto;
        }

        .alert.alert-danger {
            width: 80%;
            margin: 1em auto;
        }

        .alert.alert-danger ul{
            list-style-type: none;
            text-align: center;
        }
    </style>
{% endblock %}